// Generated by CoffeeScript 1.7.1
(function() {
  var b, input;

  input = $('#movie_date').val();

  b = $.ajax("http://www.omdbapi.com/?t=cat", {
    dataType: 'json'
  });

  console.log(b);

  b.done(function(data) {
    console.log(data.title);
    return $('body').append("d" + data);
  });

}).call(this);

//# sourceMappingURL=main.map
